spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?? ??? (?? ?? ??)
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    # ?? ???
    #url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY}
  auth-type: Bearer
  authorities-key: auth
  access-token-header: Authorization
  refresh-token-header: RefreshToken
  access-token-expire: 86400000  # 24시간 (밀리초)
  refresh-token-expire: 604800000  # 7일 (밀리초)

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: us-east-1
    s3:
      bucket: ${AWS_S3_BUCKET}


springdoc:
  swagger-ui:
    enabled: true


gemini:
  project-id: ${GEMINI_PROJECT_ID}
  location: ${GEMINI_LOCATION}
  model: ${GEMINI_MODEL}
  api-key: ${GEMINI_API_KEY}
  key-file: ${GEMINI_API_KEY}
